routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/artisan', 'WebArtisanController@index');
Route::post('/artisan', 'WebArtisanController@run')->name('artisan.run');

Route::resource('contact', 'ContactController');
Route::resource('guardian', 'GuardianController');
Route::resource('course', 'CourseController');
Route::resource('subject', 'SubjectController');
Route::resource('batch', 'BatchController');
Route::resource('teacher', 'TeacherController');
Route::resource('student', 'StudentController');
Route::resource('room', 'RoomController');
Route::resource('classes', 'ClassesController');
Route::resource('applicant', 'ApplicantController');

Route::get('academic', 'AcademicController@index')->name('academic.index');
Route::get('academic/classes', 'AcademicController@classes')->name('academic.classes');
Route::get('academic/courses', 'AcademicController@courses')->name('academic.courses');
Route::post('search/students', 'StudentController@search')->name('student.search');

Route::get('financial', 'AccountController@index')->name('financial.index');
Route::resource('account', 'AccountController');
Route::resource('transaction', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use App\Transaction;
use App\TransactionData;
use Illuminate\Http\Request;
use App\Http\Requests\StoreTransaction;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('transaction.index',[
            'transactions' => Transaction::with('data')->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transaction.create',[
            'accounts' => Account::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTransaction $request)
    {
        if (array_sum($request->debit) != array_sum($request->credit)) {
            return redirect()->back()->withDanger('Transaction is not balanced');
        }
        
        $transaction = Transaction::create($request->all());

        for ($i=0; $i < count($request->account); $i++) { 
            $transaction->data()->create([
                // 'account_id' => Account::whereName($request->account[$i])->first()->id,
                'account_id' => $request->account[$i],
                'amount' => $request->debit[$i] - $request->credit[$i],
            ]);
        }

        return redirect()->back()->withMessage('Transaction Recorded');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }
}

resources/views/transaction/create.blade.php
@extends('layouts.financial')

@section('content')
@include('includes.message')
@include('includes.errors')
<div class="card">
  <div class="card-body">
    <div class="card-title h3">Create Transaction</div>
    <form method="POST" action="{{ route('transaction.store') }}">
      @csrf

      <x-input type="date" name="date" :editName="date('Y-m-d')" />

      <div class="form-group">
        <div class="row">
          <label class="col-md-8">Accounts:</label>
          <label class="col-md-2 text-center">Debit</label>
          <label class="col-md-2 text-center">Credit</label>
        </div>
        <div class="row mt-1" v-for="item in items">
          <div class="col-md-8 pr-1">
            <select class="form-control form-control-lg @error('account') is-invalid @enderror" name="account[]">
              <option selected disabled>Please Select</option>
              @forelse($accounts as $account)
                  <option value="{{ $account->id }}">{{ $account->name }}</option>
              @empty
                  <option disabled>Please add accounts</option>
              @endforelse
            </select>
            @error('account')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
            <!-- <input id="" type="text" class="form-control form-control-lg" name="account[]" list="accounts"> -->
          </div>
          <div class="col-md-2 pl-0 pr-1">
            <input id="" type="number" class="form-control form-control-lg text-right" name="debit[]" value="">
          </div>
          <div class="col-md-2 pl-0">
            <input id="" type="number" class="form-control form-control-lg text-right" name="credit[]" value="">
          </div>
        </div>
      </div>

      <div class="text-right">
        <a href="#" class="text-sm" @click="items += 1">+ Add Line</a>
      </div>
      <x-input type="text" name="narration" />

      <datalist id="accounts">
        @foreach($accounts as $account)
          <option value="{{$account->name}}">
        @endforeach
      </datalist>

      <button type="submit" class="btn btn-primary">{{ __('Save Transaction') }}</button>
    </form>
  </div>
</div>
@endsection

resources/views/transaction/edit.blade.php
@extends('layouts.financial')

@section('content')
@include('includes.message')
<div class="card">
  <div class="card-body">
    <div class="card-title h3">Create Account</div>
    <form method="POST" action="{{ route('account.update', $account->id) }}">
      @csrf @method('PUT')

      <x-input type="text" name="nature" :editName="$account->nature" />
      <x-input type="text" name="category" :editName="$account->category" />
      <x-input type="text" name="control" :editName="$account->control" />
      <x-input type="text" name="name" :editName="$account->name" />

      <button type="submit" class="btn btn-primary">{{ __('Edit Account') }}</button>
      <a href="#" onclick="document.getElementById('deleteForm').submit(); return false;" class="btn btn-outline-danger">Delete</a>
    </form>
    <form id="deleteForm" action="{{route('account.destroy', $account)}}" method="post">
      @csrf @method('DELETE')
    </form>
  </div>
</div>
@endsection

resources/views/transaction/index.blade.php
@extends('layouts.financial')

@section('content')
@include('includes.message')

<div class="card">

  <div class="card-body pb-0">
    <div class="d-flex justify-content-between align-items-start">
      <div class="card-title h3">Select Voucher</div>
      <!-- <a href="{{ route('transaction.create') }}" class="btn btn-sm btn-primary">+ Create</a> -->
    </div>
  </div>

  <table class="table mb-0">
  
    <thead>
      <tr>
        <th>Voucher Name</th>
        <th>Description</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><a href="">Cash Received</a></td>
      </tr>
    </tbody>

  </table>
  
</div>

@endsection