routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/artisan', 'WebArtisanController@index');
Route::post('/artisan', 'WebArtisanController@run')->name('artisan.run');

Route::resource('contact', 'ContactController');
Route::resource('guardian', 'GuardianController');
Route::resource('course', 'CourseController');
Route::resource('subject', 'SubjectController');
Route::resource('batch', 'BatchController');
Route::resource('teacher', 'TeacherController');
Route::resource('student', 'StudentController');
Route::resource('room', 'RoomController');
Route::resource('classes', 'ClassesController');
Route::resource('applicant', 'ApplicantController');

Route::get('academic', 'AcademicController@index')->name('academic.index');
Route::get('academic/classes', 'AcademicController@classes')->name('academic.classes');
Route::get('academic/courses', 'AcademicController@courses')->name('academic.courses');
Route::post('search/students', 'StudentController@search')->name('student.search');

Route::get('financial', 'AccountController@index')->name('financial.index');
Route::resource('account', 'AccountController');
Route::resource('transaction', 'TransactionController');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    public $timestamps = false;
    protected $fillable = ['gender', 'guardian_id', 'batch_id'];

    public function contact()
    {
        return $this->morphOne(Contact::class, 'contactable');
    }

    public function guardian()
    {
        return $this->belongsTo(Guardian::class);
    }

    public function batch()
    {
        return $this->belongsTo(Batch::class);
    }

    public function getNameAttribute()
    {
        return $this->contact->name;
    }

    public function getEmailAttribute()
    {
        return $this->contact->email;
    }

    public function getPhoneAttribute()
    {
        return $this->contact->phone;
    }

    public function getAddressAttribute()
    {
        return $this->contact->address;
    }    
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Batch;
use App\Student;
use App\Guardian;
use Illuminate\Http\Request;
use App\Http\Requests\StoreStudent;
use App\Http\Requests\UpdateStudent;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('student.index', [
            'students' => Student::all(),
            'batches' => Batch::all()
        ]);
    }

    public function search(Request $request)
    {
        $request->validate([
            'id' => 'numeric|nullable',
            'batch' => 'numeric'
        ]);

        // return redirect()->route('student.index');
        return view('student.index', [
            'students' => Student::whereId($request->id)->orWhere('batch_id',$request->batch)->get(),
            'batches' => Batch::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.create',[
            'guardians' => Guardian::all(),
            'batches' => Batch::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreStudent $request)
    {
        $student = Student::create(array_merge($request->validated(),['guardian_id' => $request->guardian, 'batch_id' => $request->batch]));
        $student->contact()->create($request->validated());

        return redirect()->back()->withMessage('Student Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return view('student.show', [
            'student' => $student
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('student.edit', [
            'student' => $student,
            'guardians' => Guardian::all(),
            'batches' => Batch::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStudent $request, Student $student)
    {
        $student->update(array_merge($request->validated(),['guardian_id' => $request->guardian, 'batch_id' => $request->batch]));
        $student->contact()->update($request->only(['name', 'email', 'phone', 'address']));

        return redirect()->back()->withMessage('Student Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->contact()->delete();
        $student->delete();

        return redirect()->route('student.index');
    }
}

resources/views/student/aside.blade.php
@include('academic.aside')

resources/views/student/create.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('student.aside')
      </nav>
    </div>
</div>
<div class="col-md-6">
    @include('includes.message')

    <div class="card">
      <div class="card-body">
        <div class="card-title h3">Create Student</div>
        
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="student-tab" data-toggle="tab" href="#student" role="tab" aria-controls="student" aria-selected="true">Student</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="guardian-tab" data-toggle="tab" href="#guardian" role="tab" aria-controls="guardian" aria-selected="false">Guardian</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="batch-tab" data-toggle="tab" href="#batch" role="tab" aria-controls="batch" aria-selected="false">Batch</a>
          </li>
        </ul>
        
          <form method="POST" action="{{ route('student.store') }}">
            @csrf
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active my-4" id="student" role="tabpanel" aria-labelledby="student-tab">

                <x-input type="text" name="name" />
                <x-input type="email" name="email" />
                <x-input type="phone" name="phone" />
                <x-input type="text" name="address" />

                <div class="gender-radio-select">
                  <label class="form-label">Gender:</label>
                  <div class="form-group">
                    <div class="custom-control custom-radio custom-control-inline">
                      <input class="custom-control-input" type="radio" name="gender" id="female" value="female">
                      <label class="custom-control-label" for="female">Female</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                      <input class="custom-control-input" type="radio" name="gender" id="male" value="male">
                      <label class="custom-control-label" for="male">Male</label>
                    </div>
                  </div>
                </div>

              </div>

              <!-- Guardian Tab -->
              <div class="tab-pane fade my-4" id="guardian" role="tabpanel" aria-labelledby="guardian-tab">
                
                <!-- <x-input type="text" name="guardian_name" />
                <x-input type="email" name="guardian_email" />
                <x-input type="phone" name="guardian_phone" />
                <x-input type="text" name="guardian_address" /> -->
                <div class="form-group">
                  <label for="course" class="form-label">Guardian:</label>
                  <select class="form-control @error('guardian') is-invalid @enderror" name="guardian" id="guardian">
                    <option selected disabled>Please Select</option>
                    @forelse($guardians as $guardian)
                      <option value="{{ $guardian->id }}">{{ $guardian->name }}</option>
                    @empty
                      <option selected disabled>Please add guardian first</option>
                    @endforelse
                  </select>
                  @error('guardian')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>

              <!-- Batch Tab -->
              <div class="tab-pane fade my-4" id="batch" role="tabpanel" aria-labelledby="batch-tab">
                <div class="form-group">
                  <label for="course" class="form-label">Batch:</label>
                  <select class="form-control @error('batch') is-invalid @enderror" name="batch" id="batch">
                    <option selected disabled>Please Select</option>
                    @forelse($batches as $batch)
                      <option value="{{ $batch->id }}">{{ $batch->course->name }}-{{ $batch->session }}</option>
                    @empty
                      <option selected disabled>Please add batch first</option>
                    @endforelse
                  </select>
                  @error('batch')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>

            </div>
            <button type="submit" class="btn btn-primary">{{ __('Save Student') }}</button>
          </form>

      </div>
    </div>
</div>
@endsection

resources/views/student/edit.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('student.aside')
      </nav>
    </div>
</div>
<div class="col-md-6">
    @include('includes.message')

    <div class="card">
      <div class="card-body">
        <div class="card-title h3">Edit Student</div>

        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="student-tab" data-toggle="tab" href="#student" role="tab" aria-controls="student" aria-selected="true">Student</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="guardian-tab" data-toggle="tab" href="#guardian" role="tab" aria-controls="guardian" aria-selected="false">Guardian</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="batch-tab" data-toggle="tab" href="#batch" role="tab" aria-controls="batch" aria-selected="false">Batch</a>
          </li>
        </ul>

        <form method="POST" action="{{ route('student.update', $student) }}">
          @csrf @method('PUT')

          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active my-4" id="student" role="tabpanel" aria-labelledby="student-tab">

              <x-input type="text" name="name" :editName="$student->name"/>
              <x-input type="email" name="email" :editName="$student->email"/>
              <x-input type="phone" name="phone" :editName="$student->phone"/>
              <x-input type="text" name="address" :editName="$student->address"/>

              <div class="gender-radio-select">
                <label class="form-label">Gender:</label>
                <div class="form-group">
                  <div class="custom-control custom-radio custom-control-inline">
                    <input class="custom-control-input" type="radio" name="gender" id="female" value="female" @if($student->gender == 'female') checked @endif />
                    <label class="custom-control-label" for="female">Female</label>
                  </div>
                  <div class="custom-control custom-radio custom-control-inline">
                    <input class="custom-control-input" type="radio" name="gender" id="male" value="male" @if($student->gender == 'male') checked @endif>
                    <label class="custom-control-label" for="male">Male</label>
                  </div>
                </div>
              </div>

            </div>

            <!-- Guardian Tab -->
            <div class="tab-pane fade my-4" id="guardian" role="tabpanel" aria-labelledby="guardian-tab">
              <div class="form-group">
                <label for="course" class="form-label">Guardian:</label>

                <select class="form-control @error('guardian') is-invalid @enderror" name="guardian" id="guardian">
                  <option selected value="0">Please Select</option>
                  @forelse($guardians as $guardian)
                    <option value="{{ $guardian->id }}" @if($student->guardian_id == $guardian->id) selected @endif>{{ $guardian->name }}</option>
                  @empty
                    <option selected disabled>Please add guardian first</option>
                  @endforelse
                </select>

                @error('guardian')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>

            <!-- Batch Tab -->
            <div class="tab-pane fade my-4" id="batch" role="tabpanel" aria-labelledby="batch-tab">
              <div class="form-group">
                <label for="course" class="form-label">Batch:</label>
                <select class="form-control @error('batch') is-invalid @enderror" name="batch" id="batch">
                  <option selected value="0">Please Select</option>
                  @forelse($batches as $batch)
                    <option value="{{ $batch->id }}" @if($student->batch_id == $batch->id) selected @endif>{{ $batch->course->name }}-{{ $batch->session }}</option>
                  @empty
                    <option selected disabled>Please add batch first</option>
                  @endforelse
                </select>
                @error('batch')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>

          </div>

          <button type="submit" class="btn btn-primary">{{ __('Update Student') }}</button>
          <a href="#" onclick="document.getElementById('deleteForm').submit(); return false;" class="btn btn-outline-danger">Delete</a>
        </form>
        <form id="deleteForm" action="{{route('student.destroy', $student)}}" method="post">
          @csrf @method('DELETE')
        </form>
      </div>
    </div>
</div>
@endsection

resources/views/student/index.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('student.aside')
      </nav>
    </div>
</div>
<div class="col-md-9">
    @include('includes.message')

    <div class="card">
        <div class="card-body pb-0">
          <div class="d-flex justify-content-between align-items-start">
            <div class="card-title h3">Student</div>
            <div>
              <a href="{{ route('student.create') }}" class="btn btn-sm btn-primary">Add</a>
              <button type="button" class="btn btn-sm btn-secondary" data-toggle="modal" data-target="#exampleModal">Search</a>
            </div>
          </div>
        </div>

        <table class="table">
        
          <tr>
            <th>Name</th>
            <th>Guardian</th>
            <th>Gender</th>
            <th>Batch</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
          </tr>

          @forelse($students as $student)

            <tr>
              <td><a href="{{ route('student.show', $student->id) }}">{{$student->name}}</a></td>
              <td>@if($student->guardian()->exists())<a href="{{ route('guardian.show', $student->guardian->id) }}">{{ $student->guardian->name }}</a>@endif</td>
              <td>{{$student->gender}}</td>
              <td>@if($student->batch()->exists())<a href="{{ route('batch.show', $student->batch->id) }}">{{ $student->batch->course->name."-".$student->batch->session }}</a>@endif</td>
              <td>{{$student->email}}</td>
              <td>{{$student->phone}}</td>
              <td>{{$student->address}}</td>
            </tr>

          @empty
          
            <tr>
              <td colspan="7">No students found</td>
            </tr>

          @endforelse

        </table>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Search</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{ route('student.search') }}" method="post">
      @csrf
      <div class="modal-body">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="id-search-tab" href="#id-search" data-toggle="tab" href="#id-search" role="tab" aria-controls="id" aria-selected="true">By ID</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="batch-search-tab" href="#batch-search" data-toggle="tab" href="#batch-search" role="tab" aria-controls="batch" aria-selected="true">By Batch</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="id-search" role="tabpanel" aria-labelledby="id-search">
            <div class="py-3">
              <x-input type="text" name="id" />
            </div>
          </div>
          <div class="tab-pane fade" id="batch-search" role="tabpanel" aria-labelledby="batch-search">
            <div class="py-3">
              <x-select name="batch" :records="$batches" field="name" />
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Search</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/student/show.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('student.aside')
      </nav>
    </div>
</div>
<div class="col-md-6">
    @include('includes.message')

    <div class="card">
      <div class="card-body pb-0">
        <div class="card-title h3">{{ $student->name }}</div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        ID
        <span>#{{ $student->id }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Name
        <span>{{ $student->name }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Gender
        <span>{{ ucfirst($student->gender) }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Batch
        <span>{{ $student->batch()->exists() ? $student->batch->course->name."-".$student->batch->session : '' }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Guardian
        <span>{{ $student->guardian()->exists() ? $student->guardian->name : '' }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Email
        <span>{{ $student->email }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Phone
        <span>{{ $student->phone }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Address
        <span>{{ $student->address }}</span>
      </li>
    </ul>
    <div class="m-3 d-flex">
      <form action="{{route('student.destroy', $student)}}" method="post">
        @csrf @method('DELETE')
        <a href="{{route('student.edit',$student)}}" class="btn btn-primary">Edit Student</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
      </form>
    </div>
    
</div>
@endsection