routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/artisan', 'WebArtisanController@index');
Route::post('/artisan', 'WebArtisanController@run')->name('artisan.run');

Route::resource('contact', 'ContactController');
Route::resource('guardian', 'GuardianController');
Route::resource('course', 'CourseController');
Route::resource('subject', 'SubjectController');
Route::resource('batch', 'BatchController');
Route::resource('teacher', 'TeacherController');
Route::resource('student', 'StudentController');
Route::resource('room', 'RoomController');
Route::resource('classes', 'ClassesController');
Route::resource('applicant', 'ApplicantController');

Route::get('academic', 'AcademicController@index')->name('academic.index');
Route::get('academic/classes', 'AcademicController@classes')->name('academic.classes');
Route::get('academic/courses', 'AcademicController@courses')->name('academic.courses');
Route::post('search/students', 'StudentController@search')->name('student.search');

Route::get('financial', 'AccountController@index')->name('financial.index');
Route::resource('account', 'AccountController');
Route::resource('transaction', 'TransactionController');

app/Http/Controllers/AcademicController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Classes;
use App\Student;
use App\Applicant;
use Illuminate\Http\Request;

class AcademicController extends Controller
{
    public function index()
    {
        return view('academic.index',[
            'classes' => Classes::whereDate('timming',date('Y-m-d'))->get(),
            'applicants' => Applicant::whereStatus('open')->get(),
            'students' => Student::all(),
        ]);
    }

    public function classes()
    {
        return view('academic.classes',[
            'classes' => Classes::all()
        ]);
    }

    public function applicants()
    {
        return view('academic.applicants',[
            'applicants' => Applicant::all()
        ]);
    }

    public function courses()
    {
        return view('academic.courses',[
            'courses' => Course::with('subjects')->get()
        ]);
    }
}

resources/views/academic/applicants.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('academic.aside')
      </nav>
    </div>
</div>
<div class="col-md-9">
    @include('includes.message')
    <div class="card">
        <div class="card-body pb-0">
          <div class="card-title h3">Applicants</div>
        </div>

        <table class="table">
        
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Program</th>
            <th>Session</th>
            <th>Date</th>
            <th>Status</th>
          </tr>

          @forelse($applicants as $applicant)

            <tr>
              <td><a href="{{ route('applicant.show', $applicant->id) }}">{{$applicant->id}}</a></td>
              <td>{{$applicant->name}}</td>
              <td>{{$applicant->phone}}</td>
              <td>{{$applicant->course->name}}</td>
              <td class="text-capitalize">{{$applicant->message}}</td>
              <td>{{ date("d M Y",strtotime($applicant->created_at))}}</td>
              <td class="text-uppercase">{{$applicant->status}}</td>
            </tr>

          @empty
          
            <tr>
              <td colspan="40">No applicants found</td>
            </tr>

          @endforelse

        </table>
    </div>
</div>
@endsection

resources/views/academic/aside.blade.php
<a class="nav-link" href="{{ route('academic.index') }}">Overview</a>
<a class="nav-link" href="{{ route('applicant.index') }}">Applicants</a>
<a class="nav-link" href="{{ route('classes.index') }}">Classes Schedule</a>
<a class="nav-link" href="{{ route('student.index') }}">Student Data</a>
<a class="nav-link" href="{{ route('batch.index') }}">Batch Management</a>
<a class="nav-link" href="{{ route('academic.courses') }}">Courses & Subjects</a>
<a class="nav-link" href="{{ route('student.create') }}">New Registrations</a>
<a class="nav-link" href="{{ route('teacher.index') }}">Teachers</a>
<a class="nav-link" href="{{ route('room.index') }}">Classrooms</a>

resources/views/academic/classes.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('academic.aside')
      </nav>
    </div>
</div>
<div class="col-md-9">
    @include('includes.message')
    <div class="card">
        <div class="card-body pb-0">
          <div class="card-title h3">Classess</div>
        </div>

        <table class="table">
        
          <tr>
            <th>ID</th>
            <th>Batch</th>
            <th>Teacher</th>
            <th>Subject</th>
            <th>Room</th>
            <th>Date</th>
            <th>Time</th>            
            <th>Hours</th>
            <th>Status</th>
          </tr>

          @forelse($classes as $classes)

            <tr>
              <td><a href="{{route('classes.show', $classes->id)}}">#{{$classes->id}}</a></td>
              <td>{{$classes->batch->name}}</td>
              <td>{{$classes->teacher->name}}</td>
              <td>{{$classes->subject->name}}</td>
              <td>{{$classes->room->name}}</td>
              <td>{{date('d M Y', strtotime($classes->timming))}}</td>
              <td>{{date('h:i A', strtotime($classes->timming))}}</td>              
              <td>{{$classes->hours}}</td>
              <td class="text-uppercase">{{$classes->status}}</td>
            </tr>

          @empty
          
            <tr>
              <td colspan="40">No classes found</td>
            </tr>

          @endforelse

        </table>
    </div>
</div>
@endsection

resources/views/academic/courses.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('academic.aside')
      </nav>
    </div>
</div>
<div class="col-md-9">
    @include('includes.message')
    <div class="card">
      <div class="card-body pb-0">
        <div class="d-flex justify-content-between align-items-start">
          <div class="card-title h3">Courses and Subjects</div>
          <div>
            <a href="{{ route('course.create') }}" class="btn btn-sm btn-primary">New Course</a>
            <a href="{{ route('subject.create') }}" class="btn btn-sm btn-primary">New Subject</a>
          </div>
        </div>
      </div>
    </div>
    <div class="row my-3">
      @forelse($courses as $course)
        <div class="col-md-4">
          <div class="card">
            <div class="card-body pb-0  border-bottom">
              <div class="d-flex justify-content-between align-items-start">
                <div class="card-title h3">{{ $course->name }}</div>
                <a href="{{ route('course.show', $course->id) }}" class="btn btn-sm btn-outline-primary">Edit</a>
              </div>
            </div>
            <div class="list-group list-group-flush">
              @forelse($course->subjects as $subject)
                <a href="{{route('subject.show',$subject->id)}}" class="list-group-item list-group-item-action">{{ $subject->name }}</a>
              @empty
              @endforelse
            </div>
          </div>
        </div>
      @empty
        No Courses
      @endforelse
    </div>
</div>
@endsection

resources/views/academic/index.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('academic.aside')
      </nav>
    </div>
</div>
<div class="col-md-9">
    @include('includes.message')
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center">{{ $applicants->count() }}</h2>
          <h5 class="card-title text-center">Open Registrations</h5>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center">{{ $classes->count() }}</h2>
          <h5 class="card-title text-center">Classes Today</h5>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center">{{ $students->count() }}</h2>
          <h5 class="card-title text-center">Active Students</h5>
        </div>
      </div>
    </div>

    <div class="card my-3">
        <div class="card-body pb-0">
          <div class="card-title h3">Classess Today</div>
        </div>

        <table class="table">
        
          <tr>
            <th>ID</th>
            <th>Batch</th>
            <th>Teacher</th>
            <th>Subject</th>
            <th>Room</th>
            <th>Date</th>
            <th>Time</th>            
            <th>Hours</th>
            <th>Status</th>
          </tr>

          @forelse($classes as $classes)

            <tr>
              <td><a href="{{route('classes.show', $classes->id)}}">#{{$classes->id}}</a></td>
              <td>{{$classes->batch->name}}</td>
              <td>{{$classes->teacher->name}}</td>
              <td>{{$classes->subject->name}}</td>
              <td>{{$classes->room->name}}</td>
              <td>{{date('d M Y', strtotime($classes->timming))}}</td>
              <td>{{date('h:i A', strtotime($classes->timming))}}</td>              
              <td>{{$classes->hours}}</td>
              <td class="text-uppercase">{{$classes->status}}</td>
            </tr>

          @empty
          
            <tr>
              <td colspan="40">No classes found</td>
            </tr>

          @endforelse

        </table>
    </div>
</div>
@endsection