routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/artisan', 'WebArtisanController@index');
Route::post('/artisan', 'WebArtisanController@run')->name('artisan.run');

Route::resource('contact', 'ContactController');
Route::resource('guardian', 'GuardianController');
Route::resource('course', 'CourseController');
Route::resource('subject', 'SubjectController');
Route::resource('batch', 'BatchController');
Route::resource('teacher', 'TeacherController');
Route::resource('student', 'StudentController');
Route::resource('room', 'RoomController');
Route::resource('classes', 'ClassesController');
Route::resource('applicant', 'ApplicantController');

Route::get('academic', 'AcademicController@index')->name('academic.index');
Route::get('academic/classes', 'AcademicController@classes')->name('academic.classes');
Route::get('academic/courses', 'AcademicController@courses')->name('academic.courses');
Route::post('search/students', 'StudentController@search')->name('student.search');

Route::get('financial', 'AccountController@index')->name('financial.index');
Route::resource('account', 'AccountController');
Route::resource('transaction', 'TransactionController');

app/Guardian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Guardian extends Model
{
    public $timestamps = false;
    protected $fillable = ['occupation'];

    public function contact()
    {
        return $this->morphOne(Contact::class, 'contactable');
    }

    public function getNameAttribute()
    {
        return $this->contact->name;
    }

    public function getEmailAttribute()
    {
        return $this->contact->email;
    }

    public function getPhoneAttribute()
    {
        return $this->contact->phone;
    }

    public function getAddressAttribute()
    {
        return $this->contact->address;
    }
}

app/Http/Controllers/GuardianController.php
<?php

namespace App\Http\Controllers;

use App\Guardian;
use Illuminate\Http\Request;
use App\Http\Requests\StoreGuardian;
use App\Http\Requests\UpdateGuardian;

class GuardianController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('guardian.index', [
            'guardians' => Guardian::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('guardian.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreGuardian $request)
    {
        $guardian = Guardian::create($request->validated());
        $guardian->contact()->create($request->validated());

        return redirect()->back()->withMessage('Guardian Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Guardian  $guardian
     * @return \Illuminate\Http\Response
     */
    public function show(Guardian $guardian)
    {
        return view('guardian.show', [
            'guardian' => $guardian
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Guardian  $guardian
     * @return \Illuminate\Http\Response
     */
    public function edit(Guardian $guardian)
    {
        return view('guardian.edit', [
            'guardian' => $guardian
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Guardian  $guardian
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateGuardian $request, Guardian $guardian)
    {
        $guardian->update($request->all());
        $guardian->contact()->update($request->only(['name', 'email', 'phone', 'address']));

        return redirect()->back()->withMessage('Guardian Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Guardian  $guardian
     * @return \Illuminate\Http\Response
     */
    public function destroy(Guardian $guardian)
    {
        $guardian->contact()->delete();
        $guardian->delete();

        return redirect()->route('guardian.index');
    }
}

resources/views/guardian/aside.blade.php
<a class="nav-link" href="{{ route('guardian.index') }}">Overview</a>
<a class="nav-link" href="{{ route('guardian.create') }}">Create</a>

resources/views/guardian/create.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('guardian.aside')
      </nav>
    </div>
</div>
<div class="col-md-6">
    @include('includes.message')

    <div class="card">
      <div class="card-body">
        <div class="card-title h3">Create Guardian</div>
        <form method="POST" action="{{ route('guardian.store') }}">
          @csrf

          <x-input type="text" name="name" />
          <x-input type="text" name="occupation" />
          <x-input type="email" name="email" />
          <x-input type="phone" name="phone" />
          <x-input type="text" name="address" />

          <button type="submit" class="btn btn-primary">{{ __('Save Guardian') }}</button>
        </form>
      </div>
    </div>
</div>
@endsection

resources/views/guardian/edit.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('guardian.aside')
      </nav>
    </div>
</div>
<div class="col-md-6">
    @include('includes.message')

    <div class="card">
      <div class="card-body">
        <div class="card-title h3">Edit Guardian</div>
        <form method="POST" action="{{ route('guardian.update', $guardian) }}">
          @csrf @method('PUT')

          <x-input type="text" name="name" :editName="$guardian->name" />
          <x-input type="text" name="occupation" :editName="$guardian->occupation" />
          <x-input type="email" name="email" :editName="$guardian->email" />
          <x-input type="phone" name="phone" :editName="$guardian->phone" />
          <x-input type="text" name="address" :editName="$guardian->address" />

          <button type="submit" class="btn btn-primary">{{ __('Update Guardian') }}</button>
          <a href="#" onclick="document.getElementById('deleteForm').submit()" class="btn btn-outline-danger">Delete</a>
        </form>
        <form id="deleteForm" action="{{route('guardian.destroy', $guardian)}}" method="post">
          @csrf @method('DELETE')
        </form>
      </div>
    </div>
</div>
@endsection

resources/views/guardian/index.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('guardian.aside')
      </nav>
    </div>
</div>
<div class="col-md-9">
    @include('includes.message')

    <div class="card">
        <div class="card-body pb-0">
          <div class="card-title h3">Guardians</div>
        </div>

        <table class="table">
        
          <tr>
            <th>Name</th>
            <th>Occupation</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
          </tr>

          @forelse($guardians as $guardian)

            <tr>
              <td><a href="{{ route('guardian.show', $guardian->id) }}">{{$guardian->name}}</a></td>
              <td>{{$guardian->occupation}}</td>
              <td>{{$guardian->email}}</td>
              <td>{{$guardian->phone}}</td>
              <td>{{$guardian->address}}</td>
            </tr>

          @empty
          
            <tr>
              <td colspan="4">No guardians found</td>
            </tr>

          @endforelse

        </table>
    </div>
</div>
@endsection

resources/views/guardian/show.blade.php
@extends('layouts.page')

@section('content')
<div class="col-md-3">
  <div class="card">
      <nav class="nav flex-column">
        @include('guardian.aside')
      </nav>
    </div>
</div>
<div class="col-md-6">
    @include('includes.message')

    <div class="card">
      <div class="card-body pb-0">
        <div class="card-title h3">{{ $guardian->name }}</div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        ID
        <span>#{{ $guardian->id }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Name
        <span>{{ $guardian->name }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Occupation
        <span>{{ $guardian->occupation }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Email
        <span>{{ $guardian->email }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Phone
        <span>{{ $guardian->phone }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Address
        <span>{{ $guardian->address }}</span>
      </li>
    </ul>
    <div class="m-3 d-flex">
      <form action="{{route('guardian.destroy', $guardian)}}" method="post">
        @csrf @method('DELETE')
        <a href="{{route('guardian.edit',$guardian)}}" class="btn btn-primary">Edit guardian</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
      </form>
    </div>
    
</div>
@endsection